http:
  routers:
    fpm-router:
      rule: "PathPrefix(`/`)"
      service: "fpm"
      entryPoints:
        - "fpm"

  services:
    fpm:
      loadBalancer:
        servers:
          - url: "http://fpm:80"

tcp:
  routers:
    mysql-router:
      rule: "HostSNI(`*`)"
      service: "mysql"
      entryPoints:
        - "mysql"

  services:
    mysql:
      loadBalancer:
        servers:
          - address: "mysql:3306"
