export const contents = [
  {
    src: "/awards/silver.svg",
    alt: "award-1",
    title: "30 место по России. Рейтинг Рунета, 2025",
    text: "Разработка сайтов и веб-сервисов в среднем ценовом сегменте",
    width: 48,
    height: 46,
  },
  {
    src: "/awards/silver.svg",
    alt: "award-2",
    title: "30 место по России. Рейтинг Рунета, 2025",
    text: "Разработка решений на базе ИИ",
    width: 48,
    height: 46,
  },
  {
    src: "/awards/gold.svg",
    alt: "award-3",
    title: "Золото. Рейтинг рунета, 2025",
    text: "Разработка и интеграция CRM / Барнаул",
    width: 48,
    height: 46,
  },
  {
    src: "/awards/gold.svg",
    alt: "award-4",
    title: "Золото. Рейтинг рунета, 2025",
    text: "Разработка интернет-магазинов / Барнаул",
    width: 48,
    height: 46,
  },
  {
    src: "/awards/gold.svg",
    alt: "award-5",
    title: "Золото. Рейтинг рунета, 2025",
    text: "Разработка сайтов и веб-сервисов / Барнаул",
    width: 48,
    height: 46,
  },
  {
    src: "/awards/gold.svg",
    alt: "award-6",
    title: "Золото. Рейтинг рунета, 2025",
    text: "Разработка решений на базе ИИ / Барнаул",
    width: 48,
    height: 46,
  },
  {
    src: "/awards/x.svg",
    alt: "award-7",
    title: "Серебро. Золотой сайт XXVI",
    text: "Сайт телекоммуникационной компании / Комфортел",
    subText: "Комфортел",
    svg: "/awards/arrow.svg",
    width: 68,
    height: 28,
  },
  {
    src: "/awards/award.svg",
    alt: "award-8",
    title: "Серебро. Ruward Award, 2025",
    text: "Кейс года / Форкагро",
    subText: "Форкагро",
    svg: "/awards/arrow.svg",
    width: 47,
    height: 55,
  },
  {
    src: "/awards/bronze.svg",
    alt: "award-9",
    title: "Бронза. Tagline, 2025",
    text: "Лучшая разработка / интеграция",
    subText: "Форкагро",
    svg: "/awards/arrow.svg",
    width: 48,
    height: 46,
  },
];
